file_format: "1"
id: housekeys38
name: housekeys38
type: shield
url: https://github.com/erikskinnari/housekeys/
requires: [pro_micro]
features:
  - keys
siblings:
  - housekeys38_left
  - housekeys38_right
